extends Node

func _ready():
	pass
#This is my last day in New Mexico.  The Land of Enchantment.  I am partially enchanted but never fully complete without the company of you. If you receive this before you see me that means I am lying down.  I found this gift for you in a consignment shop but only liked it because it reminded me of football.  I hate football, but I give you this with nothing but love.  There is a tumble weed outside.  I have got to go.
#Have a lovely trip.  I hope that you can find the peace and perspective that you need to be happy.  Selfishly, I hope that includes me.  Selflessly, I want to support you in acknowledging what you need.  Much love and sweet intentions.
#We have been together for eleven months today.  Or, at least, eleven months since we first slept together.  She told me a story about her coworkers throwing food and snow at her and at each other.  Lauren called me today, by accident.  I was scheduled for an interview.  I finished the spec sheets and designed a contact card.  I cooked myself a wonderful dinner of rice and brandy and vegetables and candy canes.  I am now out of Brandy.  I read one half of the last comic that Heathers father published.  Heather did not answer last time I wrote. I have been the only one showing up to work, besides Warren on Monday, because of the beautiful snowstorm on Friday and Tuesday.
#
#Last night I dreamt I got to Osaka Japan and was skateboarding around the town square.  I found some little convenience store that had a big massage bed.  The man, later introducing himself as Otis North told me what I should do, gave me a free massage, and with one finger pushed my head into the chair for maximum benefit.  The group I was with came into the shop and queued to continue.  Mel Mackie looking like Racheal Maddow led the group with her girlfriend, speaking loudly about the importance of being nice to local cultures so they will support your projects.  Otis North followed us to what was evidently a costume party, as different folk kept introducing themselves wearing bizarre outfits.  The march progressed over a field and over a river, over which one could swim, swing or climb onto a rickety rope bridge.  I began to do the last, and then woke up.  Friday we celebrated my mothers birthday.  She hurt her leg and we played games all day.  Thursday was my last day at the job, today my first at the new one.  I played games and frisbee with my brother thursday and saturday.  He smokes too much.  
#It felt like I was doing nothing all morning.  At one point a very young mother whose baby daddy is in jail was freaking out over her epidural.  But she is finally comfortable now.  Then I got to observe another c section.  This was a slightly higher risk case than usual, but it seemed to go fine.  It is kind of awesome that I have only five more hours left on this shift.  And there is another c section in just a little bit.  I wonder if they're going to let me help sew her shut.  And so far this morning I have only been snarked at by one nurse, and one of the snarkiest nurses on the floor actually said thank you to me.
